// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fin_state_analytical/features/financial_analyzer/data/models/raw_finalcial.data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(RawFinancialDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(RawFinancialDataAdapter());
  }
}
